Update check.yml

diff --git a/.github/workflows/check.yml b/.github/workflows/check.yml
--- a/.github/workflows/check.yml
+++ b/.github/workflows/check.yml
@@ -11,7 +11,7 @@ jobs:
     steps:
     - uses: actions/checkout@v4
       with:
-        fetch-depth: 0 # 👈 Обязательно скачиваем историю коммитов, чтобы можно было синхронизироваться
+        fetch-depth: 0
     - uses: actions/setup-python@v5
       with:
         python-version: '3.10'
@@ -20,14 +20,6 @@ jobs:
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         git add cleaned_sub.txt
-        
-        # Проверяем, есть ли изменения в файле
-        if ! git diff --staged --quiet; then
-          git commit -m "Auto-update servers"
-          # 👈 Скачиваем последние новшества с GitHub перед отправкой (решает ту самую ошибку)
-          git pull --rebase origin main
-          # Отправляем обновленный файл
-          git push
-        else
-          echo "Нет новых изменений для сохранения"
-        fi
+        # КОМАНДА НИЖЕ РЕШАЕТ ОШИБКУ "FAILED TO PUSH", синхронизируя репозиторий:
+        git pull --rebase origin main
+        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update servers" && git push)
